---
title: "Cine"
---

**1895 L'arrivée d'un train**
[Auguste & Louis Lumière](https://en.wikipedia.org/wiki/Auguste_and_Louis_Lumi%C3%A8re){target="_blank"}
[Extract](https://www.youtube.com/watch?v=BQjh8z9ioEw){target="_blank"} 
[Wikipedia](https://fr.wikipedia.org/wiki/L%27Arriv%C3%A9e_d%27un_train_en_gare_de_La_Ciotat){target="_blank"}

**1902 Le voyage dans la lune**
[Georges Méliès](https://en.wikipedia.org/wiki/Georges_M%C3%A9li%C3%A8s){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=5_xcB0-y10E){target="_blank"} 
[Wikipedia](https://en.wikipedia.org/wiki/A_Trip_to_the_Moon){target="_blank"}

**1920 The Cabinet of Dr. Caligari**
[Robert Wiene](https://en.wikipedia.org/wiki/Robert_Wiene){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=IAtpxqajFak){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Cabinet_of_Dr._Caligari){target="_blank"}

**1923 Always Tell Your Wife**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"} & [Seymour Hicks](https://en.wikipedia.org/wiki/Seymour_Hicks){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=cMkX17P6TVI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Always_Tell_Your_Wife){target="_blank"}

**1923 Woman to Woman**
[Graham Cutts](https://en.wikipedia.org/wiki/Graham_Cutts){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=X1TXdlEGqX0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Woman_to_Woman_(1923_film)){target="_blank"}

**1925 Battleship Potemkin**
[Sergei Eisenstein](https://en.wikipedia.org/wiki/Sergei_Eisenstein){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=2j5PzBitIGI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Battleship_Potemkin){target="_blank"}

**1927 Sunrise**
[Friedrich Wilhelm Murnau](https://en.wikipedia.org/wiki/F._W._Murnau){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=XHDe_BHH2qo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Sunrise:_A_Song_of_Two_Humans){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=6NayFytQeBE){target="_blank"}

**1927 The Lodger**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=2qFiw5VtmyI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Lodger:_A_Story_of_the_London_Fog){target="_blank"}

**1927 Napoléon**
[Abel Gance](https://en.wikipedia.org/wiki/Abel_Gance){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6504eRh5h6M){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Napoleon_(1927_film)){target="_blank"}

**1929 Un chien andalou**
[Luis Buñuel](https://en.wikipedia.org/wiki/Luis_Bu%C3%B1uel){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=JbBfHy2qNeA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Un_Chien_Andalou){target="_blank"}

**1931 City Lights**
[Charlie Chaplin](https://en.wikipedia.org/wiki/Charlie_Chaplin){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=7vl7F8S4cpQ){target="_blank"}
[Boxing scene](https://www.youtube.com/watch?v=o9NfXIXzgnA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/City_Lights){target="_blank"}

**1935 Triumph of the Will**
[Leni Riefenstahl](https://en.wikipedia.org/wiki/Leni_Riefenstahl){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=76AqxVYGGzg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Triumph_of_the_Will){target="_blank"}

**1935 The 39 Steps**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=RmSdum4BMqI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_39_Steps_(1935_film)){target="_blank"}

**1937 Young and Innocent**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=eUkE_v8l4K4){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Young_and_Innocent){target="_blank"}

**1939 Wuthering Heights**
[William Wyler](https://en.wikipedia.org/wiki/William_Wyler){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=XmuMd4FnnYo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Wuthering_Heights_(1939_film)){target="_blank"}

**1940 The Letter**
[William Wyler](https://en.wikipedia.org/wiki/William_Wyler){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=qEWK9c-c12E){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Letter_(1940_film)){target="_blank"}

**1941 Invisible Ghost**
[Joseph H. Lewis](https://en.wikipedia.org/wiki/Joseph_H._Lewis){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=b8zuKPcdVWE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Invisible_Ghost){target="_blank"}

**1941 The Little Foxes**
[William Wyler](https://en.wikipedia.org/wiki/William_Wyler){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=d_Lfa4jyTCI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Little_Foxes_(film)){target="_blank"}

**1944 Bon Voyage**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=zvDe9qQxGCU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Bon_Voyage_(1944_film)){target="_blank"}

**1945 Spellbound**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=HIBaGIUbXqI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Spellbound_(1945_film)){target="_blank"}

**1946 Shock**
[Alfred L. Werker](https://en.wikipedia.org/wiki/Alfred_L._Werker){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=lZuHHzKdovM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Shock_(1946_film)){target="_blank"}

**1946 Notorious**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=P27Za29Z2Q4){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Notorious_(1946_film)){target="_blank"}

**1948 Rope**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=8xkQoH8QbVs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Rope_(film)){target="_blank"}

**1948 Drunken Angel**
[Akira Kurosawa](https://en.wikipedia.org/wiki/Akira_Kurosawa){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=gwqzBTTn-Uo){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=-FYhv39l8jE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Drunken_Angel){target="_blank"}

**1951 Europe '51**
[Roberto Rossellini](https://en.wikipedia.org/wiki/Roberto_Rossellini){target="_blank"}
[Clip](https://www.youtube.com/watch?v=RYfj2VInZJY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Europe_%2751){target="_blank"}

**1954 Johnny Guitar**
[Nicholas Ray](https://en.wikipedia.org/wiki/Nicholas_Ray){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=xVLDdyMYyH0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Johnny_Guitar){target="_blank"}

**1954 On the Waterfront**
[Elia Kazan](https://en.wikipedia.org/wiki/Elia_Kazan){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=boekTHsOIY8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/On_the_Waterfront){target="_blank"}

**1956 Forbidden Planet**
[Fred M. Wilcox](https://en.wikipedia.org/wiki/Fred_M._Wilcox){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=AxQ9GG6hUDM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Forbidden_Planet){target="_blank"}

**1956 High Society**
[Charles Walters](https://en.wikipedia.org/wiki/Charles_Walters){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=jU9SfpVOuSQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/High_Society_(1956_film)){target="_blank"}

**1957 The Incredible Shrinking Man**
[Jack Arnold](https://en.wikipedia.org/wiki/Jack_Arnold){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=VnDfrveCADo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Incredible_Shrinking_Man){target="_blank"}

**1957 12 Angry Men**
[Sidney Lumet](https://en.wikipedia.org/wiki/Sidney_Lumet){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=TEN-2uTi2c0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/12_Angry_Men_(1957_film)){target="_blank"}

**1958 The Blob**
[Irvin S. Yeaworth Jr.](https://en.wikipedia.org/wiki/Irvin_S._Yeaworth_Jr.){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=J-heIT3L9Qg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Blob){target="_blank"}

**1958 Ashes and Diamonds**
[Andrzej Wajda](https://en.wikipedia.org/wiki/Andrzej_Wajda){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=L6CAOVuO-t0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Ashes_and_Diamonds_(film)){target="_blank"}

**1958 Vertigo**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Z5jvQwwHQNY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Vertigo_(film)){target="_blank"}

**1959 Hiroshima mon amour**
[Alain Resnais](https://en.wikipedia.org/wiki/Alain_Resnais){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=CLts830aLlw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Hiroshima_mon_amour){target="_blank"}

**1959 House on Haunted Hill**
[William Castle](https://en.wikipedia.org/wiki/William_Castle){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=GZ5paTwRA_k){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/House_on_Haunted_Hill){target="_blank"}

**1959 A Bucket of Blood**
[Roger Corman](https://en.wikipedia.org/wiki/Roger_Corman){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=hEfzyjJe0iY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/A_Bucket_of_Blood){target="_blank"}

**1959 Some Like It Hot**
[Billy Wilder](https://en.wikipedia.org/wiki/Billy_Wilder){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=97TYs2YXbJw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Some_Like_It_Hot){target="_blank"}

**1961 Battle of the Worlds**
[Antonio Margheriti](https://en.wikipedia.org/wiki/Antonio_Margheriti){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=tvBGn21Ew_s){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Battle_of_the_Worlds){target="_blank"}

**1961 Splendor in the Grass**
[Elia Kazan](https://en.wikipedia.org/wiki/Elia_Kazan){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=s-CKnxqdRZg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Splendor_in_the_Grass){target="_blank"}

**1961 The Innocents**
[Jack Clayton](https://en.wikipedia.org/wiki/Jack_Clayton){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=uouySO_LcbU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Innocents_(1961_film)){target="_blank"}

**1962 What Ever Happened to Baby Jane?**
[Robert Aldrich](https://en.wikipedia.org/wiki/Robert_Aldrich){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=3qFYjkFCxiE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/What_Ever_Happened_to_Baby_Jane%3F_(1962_film)){target="_blank"}

**1962 La Jetée**
[Chris Marker](https://en.wikipedia.org/wiki/Chris_Marker){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6anMLFwHFqs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/La_Jet%C3%A9e){target="_blank"}

**1962 Lawrence of Arabia**
[David Lean](https://en.wikipedia.org/wiki/David_Lean){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=vOlRhGEhG7k){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Lawrence_of_Arabia_(film)){target="_blank"}

**1963 The Birds**
[Alfred Hitchcock](https://en.wikipedia.org/wiki/Alfred_Hitchcock){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=nL3-lGutyYY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Birds_(film)){target="_blank"}

**1964 Dr. Strangelove**
[Stanley Kubrick](https://en.wikipedia.org/wiki/Stanley_Kubrick){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=jPU1AYTxwg4){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Dr._Strangelove){target="_blank"}

**1964 Devil Doll**
[Lindsay Shonteff](https://en.wikipedia.org/wiki/Lindsay_Shonteff){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=B0LwRto1S4o){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=he2r-ahfxeg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Devil_Doll_(film)){target="_blank"}

**1965 Crónica de un niño solo**
[Leonardo Favio](https://en.wikipedia.org/wiki/Leonardo_Favio){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=VDGUX7zRqGs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Chronicle_of_a_Boy_Alone){target="_blank"}

**1966 This Property Is Condemned**
[Sydney Pollack](https://en.wikipedia.org/wiki/Sydney_Pollack){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=t4Rb4Ji9U9k){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/This_Property_Is_Condemned){target="_blank"}

**1967 Belle de jour**
[Luis Buñuel](https://en.wikipedia.org/wiki/Luis_Bu%C3%B1uel){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=gC1lO7lqMuw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Belle_de_Jour_(film)){target="_blank"}

**1968 Targets**
[Peter Bogdanovich](https://en.wikipedia.org/wiki/Peter_Bogdanovich){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=oiSc3xAXX5g){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Targets){target="_blank"}

**1968 Hasta el Viento Tiene Miedo**
[Carlos Enrique Taboada](https://es.wikipedia.org/wiki/Carlos_Enrique_Taboada){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=yIsIwnbD0-s){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=04Ak42Qkgc0){target="_blank"}
[Wikipedia](https://es.wikipedia.org/wiki/Hasta_el_viento_tiene_miedo_(pel%C3%ADcula_de_1968)){target="_blank"}

**1968 Ayúdeme usted compadre**
[Germán Becker](https://es.wikipedia.org/wiki/Germ%C3%A1n_Becker_Ureta){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=8TLuif9XCpM){target="_blank"}
[Wikipedia](https://es.wikipedia.org/wiki/Ay%C3%BAdeme_usted_compadre){target="_blank"}

**1969 Eye of the Cat**
[David Lowell Rich](https://en.wikipedia.org/wiki/David_Lowell_Rich){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ixQPkzbt-NM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Eye_of_the_Cat){target="_blank"}

**1969 Midnight Cowboy**
[John Schlesinger](https://en.wikipedia.org/wiki/John_Schlesinger){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=o29GST0Lj28){target="_blank"}
[Comentario](https://www.youtube.com/watch?v=o8CYh7n582I){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Midnight_Cowboy){target="_blank"}

**1970 Colossus: The Forbin Project**
[Joseph Sargent](https://en.wikipedia.org/wiki/Joseph_Sargent){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=kyOEwiQhzMI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Colossus:_The_Forbin_Project){target="_blank"}

**1971 Melody**
[Waris Hussein](https://en.wikipedia.org/wiki/Waris_Hussein){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=918-ZXTDzgo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Melody_(1971_film)){target="_blank"}

**1972 Solaris**
[Andrei Tarkovsky](https://en.wikipedia.org/wiki/Andrei_Tarkovsky){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=wT8Y7DGQn7M){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Solaris_(1972_film)){target="_blank"}

**1973 Soylent Green**
[Richard Fleischer](https://en.wikipedia.org/wiki/Richard_Fleischer){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=N_jGOKYHxaQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Soylent_Green){target="_blank"}

**1974 C'eravamo tanto amati**
[Ettore Scola](https://en.wikipedia.org/wiki/Ettore_Scola){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=L5E8xkpQsMs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/We_All_Loved_Each_Other_So_Much){target="_blank"}

**1974 Lacombe, Lucien**
[Louis Malle](https://en.wikipedia.org/wiki/Louis_Malle){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=J7ZHtmyt4BY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Lacombe,_Lucien){target="_blank"}

**1975 Dog Day Afternoon**
[Sidney Lumet](https://en.wikipedia.org/wiki/Sidney_Lumet){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Ne6KMHLTvik){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Dog_Day_Afternoon){target="_blank"}

**1975 Diálogos de exiliados**
[Raúl Ruiz](https://en.wikipedia.org/wiki/Ra%C3%BAl_Ruiz){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=luGPPNGYn1M){target="_blank"}
[Wikipedia](https://es.wikipedia.org/wiki/Di%C3%A1logos_de_exiliados){target="_blank"}

**1976 Quién puede matar a un niño?**
[Narciso Ibáñez Serrador](https://en.wikipedia.org/wiki/Narciso_Ib%C3%A1%C3%B1ez_Serrador){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=mIVvKbMbXXs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Who_Can_Kill_a_Child%3F){target="_blank"}

**1977 Rabid**
[David Cronenberg](https://en.wikipedia.org/wiki/David_Cronenberg){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Fr4ZLdhoQRY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Rabid_(1977_film)){target="_blank"}

**1977 A Special Day**
[Ettore Scola](https://en.wikipedia.org/wiki/Ettore_Scola){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=lyTQ0MKUy_A){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/A_Special_Day){target="_blank"}

**1977 Eraserhead**
[David Lynch](https://en.wikipedia.org/wiki/David_Lynch){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=dU7OqGCIcak){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Eraserhead){target="_blank"}

**1979 Stalker**
[Andrei Tarkovsky](https://en.wikipedia.org/wiki/Andrei_Tarkovsky){target="_blank"}
[Full movie](https://www.youtube.com/watch?v=Q3hBLv-HLEc){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Stalker_(1979_film)){target="_blank"}

**1979 Apocalypse Now**
[Francis Ford Coppola](https://en.wikipedia.org/wiki/Francis_Ford_Coppola){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=FTjG-Aux_yQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Apocalypse_Now){target="_blank"}

**1980 Somewhere in Time**
[Jeannot Szwarc](https://en.wikipedia.org/wiki/Jeannot_Szwarc){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=9uicvPZSKIM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Somewhere_in_Time_(film)){target="_blank"}

**1980 The Shining**
[Stanley Kubrick](https://en.wikipedia.org/wiki/Stanley_Kubrick){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=S014oGZiSdI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Shining_(film)){target="_blank"}

**1983 Videodrome**
[David Cronenberg](https://en.wikipedia.org/wiki/David_Cronenberg){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=UFHey3utk0I){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Videodrome){target="_blank"}

**1982 The Verdict**
[Sidney Lumet](https://en.wikipedia.org/wiki/Sidney_Lumet){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=NF-F4ys3hHE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Verdict){target="_blank"}

**1983 Scarface**
[Brian De Palma](https://en.wikipedia.org/wiki/Brian_De_Palma){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=7pQQHnqBa2E){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Scarface_(1983_film)){target="_blank"}

**1984 The Woman in Red**
[Gene Wilder](https://en.wikipedia.org/wiki/Gene_Wilder){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=fcLMGXSyLKw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Woman_in_Red_(1984_film)){target="_blank"}

**1984 Children of the Corn**
[Fritz Kiersch](https://en.wikipedia.org/wiki/Fritz_Kiersch){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Ks7AwV_uxO0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Children_of_the_Corn_(1984_film)){target="_blank"}

**1985 Witness**
[Peter Weir](https://en.wikipedia.org/wiki/Peter_Weir){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=1VhKRDNjq6o){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Witness_(1985_film)){target="_blank"}

**1985 Tampopo**
[Jūzō Itami](https://en.wikipedia.org/wiki/J%C5%ABz%C5%8D_Itami){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Aw_XfxhzsLY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Tampopo){target="_blank"}

**1986 The Sacrifice**
[Andrei Tarkovsky](https://en.wikipedia.org/wiki/Andrei_Tarkovsky){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ODJb2-PLu7Y){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Sacrifice_(1986_film)){target="_blank"}

**1986 Le Rayon vert**
[Éric Rohmer](https://en.wikipedia.org/wiki/%C3%89ric_Rohmer){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=D7mPj2AkFfI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Green_Ray_(film)){target="_blank"}

**1986 Lucas**
[David Seltzer](https://en.wikipedia.org/wiki/David_Seltzer){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=UuQZfwWyTWY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Lucas_(film)){target="_blank"}

**1987 Wings of Desire**
[Wim Wenders](https://en.wikipedia.org/wiki/Wim_Wenders){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=hAzzR2Uklok){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Wings_of_Desire){target="_blank"}

**1987 Hellraiser**
[Clive Barker](https://en.wikipedia.org/wiki/Clive_Barker){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=P7TWm3Akw-s){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Hellraiser){target="_blank"}

**1988 They Live**
[John Carpenter](https://en.wikipedia.org/wiki/John_Carpenter){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=jTK8eff1Zsk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/They_Live){target="_blank"}

**1988 976-EVIL**
[Robert Englund](https://en.wikipedia.org/wiki/Robert_Englund){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=xQT4qB-RFjk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/976-EVIL){target="_blank"}

**1988 The Serpent and the Rainbow**
[Wes Craven](https://en.wikipedia.org/wiki/Wes_Craven){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=LNRnOcW5yqs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Serpent_and_the_Rainbow_(film)){target="_blank"}

**1989 Tetsuo: The Iron Man**
[Shinya Tsukamoto](https://en.wikipedia.org/wiki/Shinya_Tsukamoto){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ShJvheZHXdI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Tetsuo:_The_Iron_Man){target="_blank"}

**1989 Do the Right Thing**
[Spike Lee](https://en.wikipedia.org/wiki/Spike_Lee){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=muc7xqdHudI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Do_the_Right_Thing){target="_blank"}

**1991 Highway to Hell**
[Ate de Jong](https://en.wikipedia.org/wiki/Ate_de_Jong){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=yGiR2TmeNYc){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Highway_to_Hell_(film)){target="_blank"}

**1991 Delicatessen**
[Jean-Pierre Jeunet](https://en.wikipedia.org/wiki/Jean-Pierre_Jeunet){target="_blank"} & [Marc Caro](https://en.wikipedia.org/wiki/Marc_Caro){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=GVL5_I4CvTc){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Delicatessen_(1991_film)){target="_blank"}

**1991 Barton Fink**
[Joel Coen](https://en.wikipedia.org/wiki/Coen_brothers){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=WK0WjWlVO9w){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Barton_Fink){target="_blank"}

**1992 Knight Moves**
[Carl Schenkel](https://en.wikipedia.org/wiki/Carl_Schenkel){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=rvDqoxMUroA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Knight_Moves){target="_blank"}

**1992 C'est arrivé près de chez vous (Man Bites Dog)**
[Rémy Belvaux](https://en.wikipedia.org/wiki/Man_Bites_Dog_(film)){target="_blank"}, [André Bonzel](https://en.wikipedia.org/wiki/Andr%C3%A9_Bonzel){target="_blank"}, [Benoît Poelvoorde](https://en.wikipedia.org/wiki/Beno%C3%AEt_Poelvoorde){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=4KNf1qyeSZE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Man_Bites_Dog_(film)){target="_blank"}

**1992 Léolo**
[Jean-Claude Lauzon](https://en.wikipedia.org/wiki/Jean-Claude_Lauzon){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=uabC1MEq0J0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/L%C3%A9olo){target="_blank"}

**1993 Groundhog Day**
[Harold Ramis](https://en.wikipedia.org/wiki/Harold_Ramis){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=GncQtURdcE4){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Groundhog_Day_(film)){target="_blank"}

**1993 Benny & Joon**
[Jeremiah S. Chechik](https://en.wikipedia.org/wiki/Jeremiah_S._Chechik){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=AH4Jk_ZJ5OM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Benny_%26_Joon){target="_blank"}

**1997 Event Horizon**
[Paul W. S. Anderson](https://en.wikipedia.org/wiki/Paul_W._S._Anderson){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=OVlnER8SxfQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Event_Horizon_(film)){target="_blank"}

**1997 Welcome to Sarajevo**
[Michael Winterbottom](https://en.wikipedia.org/wiki/Michael_Winterbottom){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=IOmm1OD2ArQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Welcome_to_Sarajevo){target="_blank"}

**1997 Funny Games**
[Michael Haneke](https://en.wikipedia.org/wiki/Michael_Haneke){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=bH2HS6uWIhQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Funny_Games_(1997_film)){target="_blank"}

**1998 Dark City**
[Alex Proyas](https://en.wikipedia.org/wiki/Alex_Proyas){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=gt9HkO-cGGo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Dark_City_(1998_film)){target="_blank"}

**1998 Le Dîner de Cons**
[Francis Veber](https://en.wikipedia.org/wiki/Francis_Veber){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=4FANGIUNbiA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Dinner_Game){target="_blank"}
[Extract](https://www.youtube.com/watch?v=hdPdyJAIXlc){target="_blank"}
[Extract](https://www.youtube.com/watch?v=UYYwaFy05-U&list=LL){target="_blank"}
[Extract](https://www.youtube.com/watch?v=HElyGTXbBUg){target="_blank"}

**1999 Magnolia**
[Paul Thomas Anderson](https://en.wikipedia.org/wiki/Paul_Thomas_Anderson){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=KnamcFv_N9Q){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Magnolia_(film)){target="_blank"}

**1999 The Thirteenth Floor**
[Josef Rusnak](https://en.wikipedia.org/wiki/The_Thirteenth_Floor){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Cbjhr-H2nxQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Thirteenth_Floor){target="_blank"}

**2001 Session 9**
[Brad Anderson](https://en.wikipedia.org/wiki/Brad_Anderson_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=LsxkRNvEbhM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Session_9){target="_blank"}

**2001 La pianiste (The Piano Teacher)**
[Michael Haneke](https://en.wikipedia.org/wiki/Michael_Haneke){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=DKpk8mzoweA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Piano_Teacher_(film)){target="_blank"}

**2004 The Woodsman**
[Nicole Kassell](https://en.wikipedia.org/wiki/Nicole_Kassell){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=eMVw1pHVMAw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Woodsman_(2004_film)){target="_blank"}

**2004 Primer**
[Shane Carruth](https://en.wikipedia.org/wiki/Shane_Carruth){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=-vD-yj9o664){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Primer_(film)){target="_blank"}

**2005 Walk the Line**
[James Mangold](https://en.wikipedia.org/wiki/James_Mangold){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=RnFrrzg1OEQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Walk_the_Line){target="_blank"}

**2005 L'enfant**
[Jean-Pierre Dardenne](https://en.wikipedia.org/wiki/Dardenne_brothers){target="_blank"} & [Luc Dardenne](https://en.wikipedia.org/wiki/Dardenne_brothers){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=T_tgS6WgyFo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/L%27Enfant_(film)){target="_blank"}

**2005 Caché**
[Michael Haneke](https://en.wikipedia.org/wiki/Michael_Haneke){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=pvT_9TqIEtM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Cach%C3%A9_(film)){target="_blank"}

**2006 The Fountain**
[Darren Aronofsky](https://en.wikipedia.org/wiki/Darren_Aronofsky){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=GXkc4RzcBbQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Fountain){target="_blank"}

**2006 The Lives of Others (Das Leben der Anderen)**
[Florian Henckel von Donnersmarck](https://en.wikipedia.org/wiki/Florian_Henckel_von_Donnersmarck){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=YsShZNHmpGE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Lives_of_Others){target="_blank"}

**2007 The Assassination of Jesse James by the Coward Robert Ford**
[Andrew Dominik](https://en.wikipedia.org/wiki/Andrew_Dominik){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6RwAWZtK5Uw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Assassination_of_Jesse_James_by_the_Coward_Robert_Ford){target="_blank"}

**2008 The Ramen Girl**
[Robert Allan Ackerman](https://en.wikipedia.org/wiki/Robert_Allan_Ackerman){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=N_XU3fHQGHI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Ramen_Girl){target="_blank"}

**2008 The Strangers**
[Bryan Bertino](https://en.wikipedia.org/wiki/Bryan_Bertino){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=BbqELQHpmQM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Strangers_(2008_film)){target="_blank"}

**2008 Blindness**
[Fernando Meirelles](https://en.wikipedia.org/wiki/Fernando_Meirelles){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=XvTvP55cxM0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Blindness_(2008_film)){target="_blank"}

**2008 Gomorra**
[Matteo Garrone](https://en.wikipedia.org/wiki/Matteo_Garrone){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=QmwUVwsAEGE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Gomorrah_(film)){target="_blank"}

**2009 The Lodger**
[David Ondaatje](https://www.imdb.com/name/nm0648545/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=R5C47hShhEI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Lodger_(2009_film)){target="_blank"}

**2009 Finale**
[John Michael Elfers](https://en.wikipedia.org/wiki/Finale_(2009_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=QXnVYcU5khs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Finale_(2009_film)){target="_blank"}

**2009 Knowing**
[Alex Proyas](https://en.wikipedia.org/wiki/Alex_Proyas){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=rlZdvQwXrOA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Knowing_(film)){target="_blank"}

**2010 Blue Valentine**
[Derek Cianfrance](https://en.wikipedia.org/wiki/Derek_Cianfrance){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=aILx69WrRhQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Blue_Valentine_(film)){target="_blank"}

**2010 Incendies**
[Denis Villeneuve](https://en.wikipedia.org/wiki/Denis_Villeneuve){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=0nycksytL1A){target="_blank"}
[Opening scene](https://www.youtube.com/watch?v=hD9KJL1zt28){target="_blank"}
[Bus scene](https://www.youtube.com/watch?v=VchTuRWMw5Q){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Incendies){target="_blank"}

**2010 The Solitude of Prime Numbers (La solitudine dei numeri primi)**
[Saverio Costanzo](https://en.wikipedia.org/wiki/Saverio_Costanzo){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=LE5puqwQ7lo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Solitude_of_Prime_Numbers){target="_blank"}

**2011 Detachment**
[Tony Kaye](https://en.wikipedia.org/wiki/Tony_Kaye_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=w7lBleOF9Pw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Detachment_(film)){target="_blank"}

**2011 Your Sister’s Sister**
[Lynn Shelton](https://en.wikipedia.org/wiki/Lynn_Shelton){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=1Na2I2b6edA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Your_Sister%27s_Sister){target="_blank"}

**2012 The Great Beauty**
[Paolo Sorrentino](https://en.wikipedia.org/wiki/Paolo_Sorrentino){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Dyt430YkQn0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Great_Beauty){target="_blank"}

**2012 Silver Linings Playbook**
[David O. Russell](https://en.wikipedia.org/wiki/David_O._Russell){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=_-P-13H5ZhA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Silver_Linings_Playbook){target="_blank"}

**2012 Seeking a Friend for the End of the World**
[Lorene Scafaria](https://en.wikipedia.org/wiki/Lorene_Scafaria){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=EmXWcXKXWBk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Seeking_a_Friend_for_the_End_of_the_World){target="_blank"}

**2012 Resolution**
[Justin Benson](https://en.wikipedia.org/wiki/Justin_Benson_and_Aaron_Moorhead){target="_blank"} & [Aaron Moorhead](https://en.wikipedia.org/wiki/Justin_Benson_and_Aaron_Moorhead){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6-5uBCIA94c){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Resolution_(film)){target="_blank"}

**2013 The Place Beyond the Pines**
[Derek Cianfrance](https://en.wikipedia.org/wiki/Derek_Cianfrance){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=G07pSbHLXgg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Place_Beyond_the_Pines){target="_blank"}

**2013 Coherence**
[James Ward Byrkit](https://en.wikipedia.org/wiki/James_Ward_Byrkit){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=kxAOewNzz-8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Coherence_(film)){target="_blank"}

**2013 Enemy**
[Denis Villeneuve](https://en.wikipedia.org/wiki/Denis_Villeneuve){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=FJuaAWrgoUY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Enemy_(2013_film)){target="_blank"}

**2013 Upstream Color**
[Shane Carruth](https://en.wikipedia.org/wiki/Shane_Carruth){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=SilYsr_3vrA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Upstream_Color){target="_blank"}

**2013 Under the Skin**
[Jonathan Glazer](https://en.wikipedia.org/wiki/Jonathan_Glazer){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=J7bAZCOk0Sc){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Under_the_Skin_(2013_film)){target="_blank"}

**2014 Cake**
[Daniel Barnz](https://en.wikipedia.org/wiki/Daniel_Barnz){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=P3IsUOSHlnU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Cake_(2014_film)){target="_blank"}

**2014 Predestination**
[Michael Spierig](https://en.wikipedia.org/wiki/Michael_Spierig){target="_blank"} & [Peter Spierig](https://en.wikipedia.org/wiki/Peter_Spierig){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=xxG-YfedrfU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Predestination_(film)){target="_blank"}

**2014 The Wait**
[M. Blash](https://en.wikipedia.org/wiki/M._Blash){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=13VjX7drnB0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Wait_(2014_film)){target="_blank"}

**2014 The Skeleton Twins**
[Craig Johnson](https://en.wikipedia.org/wiki/Craig_Johnson_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ll0pjiOjSiU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Skeleton_Twins){target="_blank"}

**2014 Mockingbird**
[Bryan Bertino](https://en.wikipedia.org/wiki/Bryan_Bertino){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=37ePQnU9Yc8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Mockingbird_(film)){target="_blank"}

**2014 Noah**
[Darren Aronofsky](https://en.wikipedia.org/wiki/Darren_Aronofsky){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6qmj5mhDwJQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Noah_(2014_film)){target="_blank"}

**2015 The Martian**
[Ridley Scott](https://en.wikipedia.org/wiki/Ridley_Scott){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ej3ioOneTy8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Martian_(film)){target="_blank"}

**2015 The Hallow**
[Corin Hardy](https://en.wikipedia.org/wiki/Corin_Hardy){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=8fDo3-mluOs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Hallow){target="_blank"}

**2015 The Blackcoat’s Daughter**
[Osgood Perkins](https://en.wikipedia.org/wiki/Osgood_Perkins_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=3IH9Jjz3jJA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Blackcoat%27s_Daughter){target="_blank"}

**2015 Mia madre**
[Nanni Moretti](https://en.wikipedia.org/wiki/Nanni_Moretti){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=SVfpt9UpOVI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Mia_Madre){target="_blank"}

**2015 Hardcore Henry**
[Ilya Naishuller](https://en.wikipedia.org/wiki/Ilya_Naishuller){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=wv33e0TyL6M){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Hardcore_Henry){target="_blank"}

**2016 Arrival**
[Denis Villeneuve](https://en.wikipedia.org/wiki/Denis_Villeneuve){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=tFMo3UJ4B4g){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Arrival_(film)){target="_blank"}

**2016 Manchester by the Sea**
[Kenneth Lonergan](https://en.wikipedia.org/wiki/Kenneth_Lonergan){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=gsVoD0pTge0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Manchester_by_the_Sea_(film)){target="_blank"}

**2016 The Monster**
[Bryan Bertino](https://en.wikipedia.org/wiki/Bryan_Bertino){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=tbyCUdzR87Y){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Monster_(2016_film)){target="_blank"}

**2016 Personal Shopper**
[Olivier Assayas](https://en.wikipedia.org/wiki/Olivier_Assayas){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ZLNUGnfGqv8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Personal_Shopper){target="_blank"}

**2016 War & Peace (TV)**
[Tom Harper](https://en.wikipedia.org/wiki/Tom_Harper_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=H-BCmUeHE5c){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/War_and_Peace_(2016_TV_series)){target="_blank"}

**2016 Swiss Army Man**
[Daniel Kwan](https://en.wikipedia.org/wiki/Daniel_Kwan){target="_blank"} & [Daniel Scheinert](https://en.wikipedia.org/wiki/Daniel_Scheinert){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=yrK1f4TsQfM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Swiss_Army_Man){target="_blank"}

**2016 Aquarius**
[Kleber Mendonça Filho](https://en.wikipedia.org/wiki/Kleber_Mendon%C3%A7a_Filho){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=0Zln78CcFkA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Aquarius_(film)){target="_blank"}

**2017 Downsizing**
[Alexander Payne](https://en.wikipedia.org/wiki/Alexander_Payne){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=UCrBICYM0yM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Downsizing_(film)){target="_blank"}

**2017 Tallo Falls**
[Patrick Magee](https://www.imdb.com/name/nm1414398/?ref_=tt_ov_dr_1){target="_blank"} 
[Trailer](https://www.youtube.com/watch?v=SrVcwvkS1Uc){target="_blank"}
[IMDb](https://www.imdb.com/title/tt5688868/){target="_blank"}

**2017 Veronica**
[Paco Plaza](https://en.wikipedia.org/wiki/Paco_Plaza){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=iMWvbW4n8mE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Ver%C3%B3nica_(2017_Spanish_film)){target="_blank"}

**2017 Time Trap**
[Mark Dennis](https://en.wikipedia.org/wiki/Time_Trap_(film)){target="_blank"} & [Ben Foster](https://en.wikipedia.org/wiki/Time_Trap_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6T3Z0JTf77k){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Time_Trap_(film)){target="_blank"}

**2017 The Shape of Water**
[Guillermo del Toro](https://en.wikipedia.org/wiki/Guillermo_del_Toro){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=XFYWazblaUA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Shape_of_Water){target="_blank"}

**2017 The Killing of a Sacred Deer**
[Yorgos Lanthimos](https://en.wikipedia.org/wiki/Yorgos_Lanthimos){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=CQFdGfwChtw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Killing_of_a_Sacred_Deer){target="_blank"}

**2017 A Ghost Story**
[David Lowery](https://en.wikipedia.org/wiki/David_Lowery_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=c_3NMtxeyfk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/A_Ghost_Story){target="_blank"}

**2017 Dan in Real Life**
[Peter Hedges](https://en.wikipedia.org/wiki/Peter_Hedges){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=8XageyLtu7g){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Dan_in_Real_Life){target="_blank"}

**2017 The Endless**
[Justin Benson](https://en.wikipedia.org/wiki/Justin_Benson){target="_blank"} & [Aaron Moorhead](https://en.wikipedia.org/wiki/Aaron_Moorhead){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=qMHpWCN0byw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Endless_(film)){target="_blank"}

**2018 Roma**
[Alfonso Cuarón](https://en.wikipedia.org/wiki/Alfonso_Cuar%C3%B3n){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6BS27ngZtxg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Roma_(2018_film)){target="_blank"}

**2018 Hereditary**
[Ari Aster](https://en.wikipedia.org/wiki/Ari_Aster){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=V6wWKNij_1M){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Hereditary_(film)){target="_blank"}

**2018 Isle of Dogs**
[Wes Anderson](https://en.wikipedia.org/wiki/Wes_Anderson){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=dt__kig8PVU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Isle_of_Dogs_(film)){target="_blank"}

**2018 The Lion Sleeps Tonight (Le Lion est mort ce soir)**
[Nobuhiro Suwa](https://en.wikipedia.org/wiki/Nobuhiro_Suwa){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=1H3oH_P9sRE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Lion_Sleeps_Tonight_(film)){target="_blank"}

**2018 Burning**
[Lee Chang-dong](https://en.wikipedia.org/wiki/Lee_Chang-dong){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=oihHs2Errwk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Burning_(film)){target="_blank"}

**2018 Border**
[Ali Abbasi](https://en.wikipedia.org/wiki/Ali_Abbasi_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=QMs28A1s1OA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Border_(2018_Swedish_film)){target="_blank"}

**2018 Black '47**
[Lance Daly](https://en.wikipedia.org/wiki/Black_%2747){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=q1W4ag4DwBs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Black_%2747){target="_blank"}

**2018 The Strangers: Prey at Night**
[Johannes Roberts](https://en.wikipedia.org/wiki/Johannes_Roberts){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=91-Z20uttEk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Strangers:_Prey_at_Night){target="_blank"}

**2018 Happy as Lazzaro (Lazzaro felice)**
[Alice Rohrwacher](https://en.wikipedia.org/wiki/Alice_Rohrwacher){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=hNqLXid6WPI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Happy_as_Lazzaro){target="_blank"}

**2018 He’s Out There**
[Quinn Lasher](https://en.wikipedia.org/wiki/He%27s_Out_There){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Bai2ktAZpM8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/He%27s_Out_There){target="_blank"}

**2019 Wounds**
[Babak Anvari](https://en.wikipedia.org/wiki/Babak_Anvari){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=81uxmIO_lps){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Wounds_(film)){target="_blank"}

**2019 Brightburn**
[David Yarovesky](https://en.wikipedia.org/wiki/David_Yarovesky){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=oD1vbhicJUY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Brightburn){target="_blank"}

**2019 The Souvenir**
[Joanna Hogg](https://en.wikipedia.org/wiki/Joanna_Hogg){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=t9Al2nC0vzY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Souvenir){target="_blank"}

**2019 Doctor Sleep**
[Mike Flanagan](https://en.wikipedia.org/wiki/Mike_Flanagan_(filmmaker)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=BOzFZxB-8cw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Doctor_Sleep_(2019_film)){target="_blank"}

**2019 Svart cirkel (Black Circle)**
[Adrián García Bogliano](https://www.imdb.com/title/tt5721636/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=K3jYTvBQNIo){target="_blank"}
[IMDb](https://www.imdb.com/title/tt5721636/){target="_blank"}

**2019 The Dead Center**
[Billy Senese](https://en.wikipedia.org/wiki/The_Dead_Center){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=DmC25jd1N5Q){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Dead_Center){target="_blank"}

**2019 Oliver Sacks: His Own Life**
[Ric Burns](https://en.wikipedia.org/wiki/Ric_Burns){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6debfd1SUA8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Oliver_Sacks:_His_Own_Life){target="_blank"}

**2019 Ma**
[Tate Taylor](https://en.wikipedia.org/wiki/Tate_Taylor){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=eIvbEC8N3cA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Ma_(2019_film)){target="_blank"}

**2019 Finale**
[Søren Juul Petersen](https://www.imdb.com/title/tt5039416/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=YOu0g__6s_0){target="_blank"}
[IMDb](https://www.imdb.com/title/tt5039416/){target="_blank"}

**2019 Harpoon**
[Rob Grant](https://en.wikipedia.org/wiki/Harpoon_(2019_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=HxQVhtm-Q9c){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Harpoon_(2019_film)){target="_blank"}

**2019 I See You**
[Adam Randall](https://en.wikipedia.org/wiki/I_See_You_(2019_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=k72fdSYHHvQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/I_See_You_(2019_film)){target="_blank"}

**2019 Fractured**
[Brad Anderson](https://en.wikipedia.org/wiki/Fractured_(2019_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=S8obCz5NSog){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Fractured_(2019_film)){target="_blank"}

**2019 Us**
[Jordan Peele](https://en.wikipedia.org/wiki/Jordan_Peele){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=hNCmb-4oXJA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Us_(2019_film)){target="_blank"}

**2019 It Must Be Heaven (De repente, el paraíso)**
[Elia Suleiman](https://en.wikipedia.org/wiki/It_Must_Be_Heaven){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=X6hXB5yUtys){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/It_Must_Be_Heaven){target="_blank"}

**2019 First Cow**
[Kelly Reichardt](https://en.wikipedia.org/wiki/First_Cow){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=SRUWVT87mt8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/First_Cow){target="_blank"}

**2019 A Night of Horror: Nightmare Radio**
[Nicolás Onetti](https://www.imdb.com/title/tt10067958/){target="_blank"} & [Luciano Onetti](https://www.imdb.com/title/tt10067958/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=9RMTYzdMiaU){target="_blank"}
[Guardian review](https://www.theguardian.com/film/2023/apr/26/nightmare-radio-the-night-stalker-review-dj-scares-up-grab-bag-of-horror-stories){target="_blank"}

**2019 Chained for Life**
[Aaron Schimberg](https://en.wikipedia.org/wiki/Aaron_Schimberg){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=mNS698-vsiQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Chained_for_Life_(2019_film)){target="_blank"}

**2019 The Lighthouse**
[Robert Eggers](https://en.wikipedia.org/wiki/Robert_Eggers){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Hyag7lR8CPA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Lighthouse_(2019_film)){target="_blank"}

**2020 Greenland**
[Ric Roman Waugh](https://en.wikipedia.org/wiki/Ric_Roman_Waugh){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=RTODtIQQRpA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Greenland_(film)){target="_blank"}

**2020 Gretel & Hansel**
[Osgood Perkins](https://en.wikipedia.org/wiki/Osgood_Perkins_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=6ZgkHjpUM8w){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Gretel_%26_Hansel){target="_blank"}

**2020 Synchronic**
[Justin Benson](https://en.wikipedia.org/wiki/Justin_Benson){target="_blank"} & [Aaron Moorhead](https://en.wikipedia.org/wiki/Aaron_Moorhead){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=XGCrg1OAYfs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Synchronic_(film)){target="_blank"}

**2020 The Wild Goose Lake**
[Diao Yinan](https://en.wikipedia.org/wiki/Diao_Yinan){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=-oCq5oa8Wzg){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Wild_Goose_Lake){target="_blank"}

**2020 Amulet**
[Romola Garai](https://en.wikipedia.org/wiki/Amulet_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=uV_lUlOc4mQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Amulet_(film)){target="_blank"}

**2020 The Antenna**
[Orçun Behram](https://www.imdb.com/title/tt8997180/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=NoMfFPok8Zw){target="_blank"}
[IMDb](https://www.imdb.com/title/tt8997180/){target="_blank"}

**2020 Possessor**
[Brandon Cronenberg](https://en.wikipedia.org/wiki/Brandon_Cronenberg){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=D0Gh9nOIV3w){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Possessor_(film)){target="_blank"}

**2020 Coma (Koma)**
[Nikita Argunov](https://en.wikipedia.org/wiki/Coma_(2020_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=5WohqZM2m8U){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Coma_(2020_film)){target="_blank"}

**2020 Double World**
[Teddy Chan](https://en.wikipedia.org/wiki/Double_World){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=i4das8_tUUY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Double_World){target="_blank"}

**2020 Tenet**
[Christopher Nolan](https://en.wikipedia.org/wiki/Christopher_Nolan){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=LdOM0x0XDMo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Tenet_(film)){target="_blank"}

**2020 Palm Springs**
[Max Barbakow](https://en.wikipedia.org/wiki/Palm_Springs_(2020_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=CpBLtXduh_k){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Palm_Springs_(2020_film)){target="_blank"}

**2020 His House**
[Remi Weekes](https://en.wikipedia.org/wiki/His_House){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=DYY0QJhlXjc){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/His_House){target="_blank"}

**2020 Archive**
[Gavin Rothery](https://en.wikipedia.org/wiki/Archive_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=I8WfXdxQ0Cw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Archive_(film)){target="_blank"}

**2020 Human Nature (documentary)**
[Adam Bolt](https://en.wikipedia.org/wiki/Human_Nature_(2019_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=ageKKE1_1Po){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Human_Nature_(2019_film)){target="_blank"}

**2020 Tengo miedo torero**
[Rodrigo Sepúlveda](https://es.wikipedia.org/wiki/Tengo_miedo_torero_(pel%C3%ADcula)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=In4hnm9X9LE){target="_blank"}
[Wikipedia](https://es.wikipedia.org/wiki/Tengo_miedo_torero_(pel%C3%ADcula)){target="_blank"}

**2020 Bloody Hell**
[Alister Grierson](https://en.wikipedia.org/wiki/Bloody_Hell_(2020_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=dnPQ7x8HxA0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Bloody_Hell_(2020_film)){target="_blank"}

**2020 The Dark and the Wicked**
[Bryan Bertino](https://en.wikipedia.org/wiki/The_Dark_and_the_Wicked){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=zM-jmNmX50Q){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Dark_and_the_Wicked){target="_blank"}

**2020 After Midnight**
[Jeremy Gardner](https://en.wikipedia.org/wiki/After_Midnight_(2019_film)){target="_blank"} & [Christian Stella](https://en.wikipedia.org/wiki/After_Midnight_(2019_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=uj8OeaGMB-8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/After_Midnight_(2019_film)){target="_blank"}

**2021 The Last Letter from Your Lover**
[Augustine Frizzell](https://en.wikipedia.org/wiki/The_Last_Letter_from_Your_Lover){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Y-I3DuUOsNw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Last_Letter_from_Your_Lover){target="_blank"}

**2021 Psycho Goreman**
[Steven Kostanski](https://en.wikipedia.org/wiki/Steven_Kostanski){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=L4tizc0IAVQ){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Psycho_Goreman){target="_blank"}

**2021 Les magnétiques (Magnetic Beats)**
[Vincent Maël Cardona](https://www.imdb.com/title/tt14068864/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=2nkgxrpcrtg){target="_blank"}
[IMDb](https://www.imdb.com/title/tt14068864/){target="_blank"}

**2021 How It Ends**
[Daryl Wein](https://en.wikipedia.org/wiki/How_It_Ends_(2021_film)){target="_blank"} & [Zoe Lister-Jones](https://en.wikipedia.org/wiki/How_It_Ends_(2021_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=CYVKc-GTTxw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/How_It_Ends_(2021_film)){target="_blank"}

**2021 The Innocents**
[Eskil Vogt](https://en.wikipedia.org/wiki/The_Innocents_(2021_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=T8HR-zTRrCM){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Innocents_(2021_film)){target="_blank"}

**2021 Carajita**
[Silvina Schnicer](https://www.imdb.com/title/tt12526902/){target="_blank"} & [Ulises Porra Guardiola](https://www.imdb.com/title/tt12526902/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=QRclqVbLD9Y){target="_blank"}
[IMDb](https://www.imdb.com/title/tt12526902/){target="_blank"}

**2021 The Machinery of Dreams**
[Eric Hurt](https://www.imdb.com/name/nm1438520/?ref_=tt_ov_dr_1){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=r3xZmn9Vz_w){target="_blank"}
[IMDb](https://www.imdb.com/title/tt7092846/){target="_blank"}

**2021 After Yang**
[Kogonada](https://en.wikipedia.org/wiki/After_Yang){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Kwp32zLc08c){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/After_Yang){target="_blank"}

**2021 Jockey**
[Clint Bentley](https://en.wikipedia.org/wiki/Jockey_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=YWI6Q-yKFbc){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Jockey_(film)){target="_blank"}

**2021 The Worst Person in the World**
[Joachim Trier](https://en.wikipedia.org/wiki/The_Worst_Person_in_the_World_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=w_cV1q02cyE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Worst_Person_in_the_World_(film)){target="_blank"}

**2022 RRR**
[S. S. Rajamouli](https://en.wikipedia.org/wiki/S._S._Rajamouli){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=f_vbAtFSEc0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/RRR_(film)){target="_blank"}

**2022 Hatching**
[Hanna Bergholm](https://en.wikipedia.org/wiki/Hatching_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=VtRNqe78x4o){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Hatching_(film)){target="_blank"}

**2022 Dual**
[Riley Stearns](https://en.wikipedia.org/wiki/Dual_(2022_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=CpZkNQ0E4YI){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Dual_(2022_film)){target="_blank"}

**2022 20th Century Girl**
[Bang Woo-ri](https://en.wikipedia.org/wiki/20th_Century_Girl){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=izClpEHwtB8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/20th_Century_Girl){target="_blank"}

**2022 Everything Everywhere All at Once**
[Daniel Kwan](https://en.wikipedia.org/wiki/Daniel_Kwan){target="_blank"} & [Daniel Scheinert](https://en.wikipedia.org/wiki/Daniel_Scheinert){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=wxN1T1uxQ2g){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Everything_Everywhere_All_at_Once){target="_blank"}

**2022 Nope**
[Jordan Peele](https://en.wikipedia.org/wiki/Jordan_Peele){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=In8fuzj3gck){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Nope_(film)){target="_blank"}

**2022 Ipersonnia**
[Alberto Mascia](https://www.imdb.com/title/tt16345046/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=iw_J2ARCH1U){target="_blank"}
[IMDb](https://www.imdb.com/title/tt16345046/){target="_blank"}

**2022 Sissy**
[Hannah Barlow](https://en.wikipedia.org/wiki/Sissy_(film)){target="_blank"} & [Kane Senes](https://en.wikipedia.org/wiki/Sissy_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=PDImh3sr9Y4){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Sissy_(film)){target="_blank"}

**2022 The Electrical Life of Louis Wain**
[Will Sharpe](https://en.wikipedia.org/wiki/The_Electrical_Life_of_Louis_Wain){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=xzDr_tbL-es){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Electrical_Life_of_Louis_Wain){target="_blank"}

**2022 Le monde d’hier**
[Diastème](https://www.imdb.com/title/tt18361872/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=rBm3DBZylQ8){target="_blank"}
[IMDb](https://www.imdb.com/title/tt18361872/){target="_blank"}

**2022 Who Invited Them**
[Duncan Birmingham](https://en.wikipedia.org/wiki/Who_Invited_Them){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Tgavhhzfsg8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Who_Invited_Them){target="_blank"}

**2022 A Man Called Otto**
[Marc Forster](https://en.wikipedia.org/wiki/Marc_Forster){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=eFYUX9l-m5I){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/A_Man_Called_Otto){target="_blank"}

**2022 Hypochondriac**
[Addison Heimann](https://www.imdb.com/title/tt12186098/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=bLyA0tRrcMo){target="_blank"}
[IMDb](https://www.imdb.com/title/tt12186098/){target="_blank"}

**2022 Skinamarink**
[Kyle Edward Ball](https://en.wikipedia.org/wiki/Skinamarink){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=APQqilSTxz0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Skinamarink){target="_blank"}

**2022 The Coffee Table (La mesita del comedor)**
[Caye Casas](https://en.wikipedia.org/wiki/The_Coffee_Table){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=oB1lTSxB2j4){target="_blank"}
[Full movie](https://m.ok.ru/video/6837050149630){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Coffee_Table){target="_blank"}

**2022 White Noise**
[Noah Baumbach](https://en.wikipedia.org/wiki/Noah_Baumbach){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=FqJD7ae11mU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/White_Noise_(2022_film)){target="_blank"}

**2023 Knock at the Cabin**
[M. Night Shyamalan](https://en.wikipedia.org/wiki/M._Night_Shyamalan){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=0wiBHEACNHs){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Knock_at_the_Cabin){target="_blank"}

**2023 Landscape with Invisible Hand**
[Cory Finley](https://en.wikipedia.org/wiki/Landscape_with_Invisible_Hand){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=lAD81wjRnL8){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Landscape_with_Invisible_Hand){target="_blank"}

**2023 Lost in the Night**
[Amat Escalante](https://en.wikipedia.org/wiki/Lost_in_the_Night){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=WqrFLiSd15o){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Lost_in_the_Night){target="_blank"}

**2023 Music for Black Pigeons (documentary)**
[Jørgen Leth](https://www.imdb.com/title/tt21376876/){target="_blank"} & [Andreas Koefoed](https://www.imdb.com/title/tt21376876/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=zEaH2gA8IoQ){target="_blank"}
[IMDb](https://www.imdb.com/title/tt21376876/){target="_blank"}

**2022 God’s Crooked Lines (Los renglones torcidos de Dios)**
[Oriol Paulo](https://en.wikipedia.org/wiki/God%27s_Crooked_Lines){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=VpZjyY4wPi0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/God%27s_Crooked_Lines){target="_blank"}

**2023 Beau Is Afraid**
[Ari Aster](https://en.wikipedia.org/wiki/Ari_Aster){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=PuiWDn976Ek){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Beau_Is_Afraid){target="_blank"}

**2023 Cuando acecha la maldad (When Evil Lurks)**
[Demián Rugna](https://es.wikipedia.org/wiki/Cuando_acecha_la_maldad){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=pOgZ-OJhwbc){target="_blank"}
[Wikipedia](https://es.wikipedia.org/wiki/Cuando_acecha_la_maldad){target="_blank"}

**2023 A Brighter Tomorrow (Il sol dell’avvenire)**
[Nanni Moretti](https://en.wikipedia.org/wiki/A_Brighter_Tomorrow){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=Tj2SzXLyADw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/A_Brighter_Tomorrow){target="_blank"}

**2023 Fallen Leaves**
[Aki Kaurismäki](https://en.wikipedia.org/wiki/Fallen_Leaves_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=a7n8IXlIcS4){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Fallen_Leaves_(film)){target="_blank"}

**2023 The Zone of Interest**
[Jonathan Glazer](https://en.wikipedia.org/wiki/The_Zone_of_Interest_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=r-vfg3KkV54){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Zone_of_Interest_%28film%29){target="_blank"}

**2023 The Settlers (Los Colonos)**
[Felipe Gálvez Haberle](https://en.wikipedia.org/wiki/The_Settlers_(2023_film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=rdy--tzaUeo){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Settlers_(2023_film)){target="_blank"}

**2023 Do Not Expect Too Much from the End of the World**
[Radu Jude](https://en.wikipedia.org/wiki/Do_Not_Expect_Too_Much_from_the_End_of_the_World){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=kd721-EpgRw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Do_Not_Expect_Too_Much_from_the_End_of_the_World){target="_blank"}

**2024 Perfect Days**
[Wim Wenders](https://en.wikipedia.org/wiki/Perfect_Days){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=QzZBbX5A1FA){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Perfect_Days){target="_blank"}

**2024 No Man’s Land (short film)**
[Full movie](https://www.youtube.com/watch?v=h5Fnlq2T0Vg){target="_blank"}

**2024 Monkey Man**
[Dev Patel](https://en.wikipedia.org/wiki/Monkey_Man_(film)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=aqa3YTtwvaU){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Monkey_Man_(film)){target="_blank"}

**2024 A Different Man**
[Aaron Schimberg](https://en.wikipedia.org/wiki/A_Different_Man){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=_9CmC5Rmsdw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/A_Different_Man){target="_blank"}

**2024 Longlegs**
[Osgood Perkins](https://en.wikipedia.org/wiki/Osgood_Perkins_(director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=LSslhT4s6ek){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Longlegs){target="_blank"}

**2024 Civil War**
[Alex Garland](https://en.wikipedia.org/wiki/Alex_Garland){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=aDyQxtg0V2w){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Civil_War_(film)){target="_blank"}

**2024 Strange Darling**
[JT Mollner](https://en.wikipedia.org/wiki/Strange_Darling){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=4wqsAwoSOd0){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Strange_Darling){target="_blank"}

**2024 Home Sweet Home**
[Thomas Sieben](https://www.imdb.com/title/tt28228001/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=DjevxU0Bx-I){target="_blank"}
[IMDb](https://www.imdb.com/title/tt28228001/){target="_blank"}

**2024 The Room Next Door**
[Pedro Almodóvar](https://en.wikipedia.org/wiki/The_Room_Next_Door){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=FLHSOFsZICk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/The_Room_Next_Door){target="_blank"}

**2024 Pimpinero: Blood and Oil**
[Andrés Baiz](https://en.wikipedia.org/wiki/Pimpinero:_Blood_and_Oil){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=YDK-ObUsPzE){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Pimpinero:_Blood_and_Oil){target="_blank"}

**2024 Heretic**
[Scott Beck](https://en.wikipedia.org/wiki/Scott_Beck_and_Bryan_Woods){target="_blank"} & [Bryan Woods](https://en.wikipedia.org/wiki/Scott_Beck_and_Bryan_Woods){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=O9i2vmFhSSY){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Heretic_(film)){target="_blank"}

**2024 Mother, Couch**
[Niclas Larsson](https://www.imdb.com/name/nm0489256/){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=nBxhpk3R2Jw){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Mother%2C_Couch){target="_blank"}

**2024 Kill the Jockey**
[Luis Ortega](https://en.wikipedia.org/wiki/Luis_Ortega_(film_director)){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=N2BSpDERJZk){target="_blank"}
[Wikipedia](https://en.wikipedia.org/wiki/Kill_the_Jockey){target="_blank"}

**2025 Denominación de Origen**
[Rodrigo Sepúlveda Urzúa](https://es.wikipedia.org/wiki/Rodrigo_Sep%C3%BAlveda_%28director_de_cine%29){target="_blank"}
[Trailer](https://www.youtube.com/watch?v=NXcXB1lJskA){target="_blank"}
[Info](https://cinechile.cl/pelicula/denominacion-de-origen/){target="_blank"}
