---
title: "Links"
---

Pelis\

1902 Le voyage dans la lune <a href="https://www.youtube.com/watch?v=5_xcB0-y10E" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/A_Trip_to_the_Moon" target="_blank">Wikipedia</a>\

1920 The Cabinet of Dr. Caligari <a href="https://www.youtube.com/watch?v=IAtpxqajFak" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Cabinet_of_Dr._Caligari" target="_blank">Wikipedia</a>\

1925 Battleship Potemkin <a href="https://www.youtube.com/watch?v=2j5PzBitIGI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Battleship_Potemkin" target="_blank">Wikipedia</a>\

1927 Napoléon <a href="https://www.youtube.com/watch?v=6504eRh5h6M" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Napoleon_(1927_film)" target="_blank">Wikipedia</a>\


1929 Un chien andalou <a href="https://www.youtube.com/watch?v=JbBfHy2qNeA" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/Un_Chien_Andalou" target="_blank">Wikipedia</a>\

1931 City lights <a href="https://www.youtube.com/watch?v=7vl7F8S4cpQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/City_Lights" target="_blank">Wikipedia</a>\ <a href="https://www.youtube.com/watch?v=o9NfXIXzgnA" target="_blank">Boxing scene</a>\

1939 Wuthering Heights <a href="https://www.youtube.com/watch?v=XmuMd4FnnYo" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Wuthering_Heights_(1939_film)" target="_blank">Wikipedia</a>\

1940 The Letter <a href="https://www.youtube.com/watch?v=qEWK9c-c12E" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Letter_(1940_film)" target="_blank">Wikipedia</a>\

1941 Invisible Ghost <a href="https://www.youtube.com/watch?v=b8zuKPcdVWE" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/Invisible_Ghost" target="_blank">Wikipedia</a>\

1941 The Little Foxes <a href="https://www.youtube.com/watch?v=d_Lfa4jyTCI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Little_Foxes_(film)" target="_blank">Wikipedia</a>\

1945 Spellbound <a href="https://www.youtube.com/watch?v=HIBaGIUbXqI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Spellbound_(1945_film)" target="_blank">Wikipedia</a>\

1946 Shock <a href="https://www.youtube.com/watch?v=lZuHHzKdovM" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/Shock_(1946_film)" target="_blank">Wikipedia</a>\

1946 Notorious <a href="https://www.youtube.com/watch?v=7LwPhO2qPcQ" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/Notorious_(1946_film)" target="_blank">Wikipedia</a>\

1948 Rope <a href="https://www.youtube.com/watch?v=8xkQoH8QbVs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Rope_%28film%29" target="_blank">Wikipedia</a>\

1948 Drunken Angel <a href="https://www.youtube.com/watch?v=U7aciSwf43o" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Drunken_Angel" target="_blank">Wikipedia</a>\ <a href="https://www.youtube.com/watch?v=-FYhv39l8jE" target="_blank">Full movie</a>\

1951 Europe '51 <a href="https://www.youtube.com/watch?v=btDP-vfiouw" target="_blank">Clip</a>\ <a href="https://en.wikipedia.org/wiki/Europe_%2751" target="_blank">Wikipedia</a>\

1954 Johnny Guitar <a href="https://www.youtube.com/watch?v=xVLDdyMYyH0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Johnny_Guitar" target="_blank">Wikipedia</a>\

1956 Forbidden Planet <a href="https://www.youtube.com/watch?v=AxQ9GG6hUDM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Forbidden_Planet" target="_blank">Wikipedia</a>\

1956 High Society <a href="https://www.youtube.com/watch?v=jU9SfpVOuSQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/High_Society_(1956_film)" target="_blank">Wikipedia</a>\

1957 The Incredible Shrinking Man <a href="https://www.youtube.com/watch?v=VnDfrveCADo" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Incredible_Shrinking_Man" target="_blank">Wikipedia</a>\

1958 The Blob <a href="https://www.youtube.com/watch?v=J-heIT3L9Qg" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Blob" target="_blank">Wikipedia</a>\

1958 Ashes and Diamonds <a href="https://www.youtube.com/watch?v=L6CAOVuO-t0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Ashes_and_Diamonds_%28film%29" target="_blank">Wikipedia</a>\

1958 Vertigo <a href="https://www.youtube.com/watch?v=Z5jvQwwHQNY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Vertigo_(film)" target="_blank">Wikipedia</a>\

1959 House on Haunted Hill <a href="https://www.youtube.com/watch?v=GZ5paTwRA_k" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/House_on_Haunted_Hill" target="_blank">Wikipedia</a>\

1959 A Bucket of Blood <a href="https://www.youtube.com/watch?v=hEfzyjJe0iY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/A_Bucket_of_Blood" target="_blank">Wikipedia</a>\

1959 Some Like It Hot <a href="https://www.youtube.com/watch?v=97TYs2YXbJw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Some_Like_It_Hot" target="_blank">Wikipedia</a>\

1961 Battle Of The Worlds <a href="https://www.youtube.com/watch?v=tvBGn21Ew_s" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Battle_of_the_Worlds" target="_blank">Wikipedia</a>\

1961 Splendor in the Grass <a href="https://www.youtube.com/watch?v=s-CKnxqdRZg" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Splendor_in_the_Grass" target="_blank">Wikipedia</a>\

1961 The Innocents #TheTurnOfTheScrew <a href="https://www.youtube.com/watch?v=uouySO_LcbU" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Innocents_(1961_film)" target="_blank">Wikipedia</a>\

1962 What Ever Happened to Baby Jane? <a href="https://www.youtube.com/watch?v=3qFYjkFCxiE" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/What_Ever_Happened_to_Baby_Jane%3F_(1962_film)" target="_blank">Wikipedia</a>\

1963 The Birds <a href="https://www.youtube.com/watch?v=nL3-lGutyYY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Birds_(film)" target="_blank">Wikipedia</a>\

1964 Dr. Strangelove <a href="https://www.youtube.com/watch?v=jPU1AYTxwg4" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Dr._Strangelove" target="_blank">Wikipedia</a>\

1965 Crónica de un niño solo <a href="https://www.youtube.com/watch?v=VDGUX7zRqGs" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/Chronicle_of_a_Boy_Alone" target="_blank">Wikipedia</a>\

1967 Belle de jour <a href="https://www.youtube.com/watch?v=gC1lO7lqMuw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Belle_de_Jour_(film)" target="_blank">Wikipedia</a>\

1968 Targets <a href="https://www.youtube.com/watch?v=oiSc3xAXX5g" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Targets" target="_blank">Wikipedia</a>\

1970 Colossus: The Forbin Project <a href="https://www.youtube.com/watch?v=kyOEwiQhzMI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Colossus:_The_Forbin_Project" target="_blank">Wikipedia</a>\

1972 Solaris <a href="https://www.youtube.com/watch?v=6-4KydP92ss" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Solaris_(1972_film)" target="_blank">Wikipedia</a>\

1973 Soylent Green <a href="https://www.youtube.com/watch?v=N_jGOKYHxaQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Soylent_Green" target="_blank">Wikipedia</a>\

1974 C'eravamo tanto amati <a href="https://www.youtube.com/watch?v=L5E8xkpQsMs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/We_All_Loved_Each_Other_So_Much" target="_blank">Wikipedia</a>\

1976 Quién puede matar a un niño? <a href="https://www.youtube.com/watch?v=mIVvKbMbXXs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Who_Can_Kill_a_Child%3F" target="_blank">Wikipedia</a>\

1977 A Special Day <a href="https://www.youtube.com/watch?v=lyTQ0MKUy_A" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/A_Special_Day" target="_blank">Wikipedia</a>\

1977 Eraserhead <a href="https://www.youtube.com/watch?v=dU7OqGCIcak" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Eraserhead" target="_blank">Wikipedia</a>\

1979 Stalker <a href="https://www.youtube.com/watch?v=Q3hBLv-HLEc" target="_blank">Full movie</a>\ <a href="https://en.wikipedia.org/wiki/Stalker_(1979_film)" target="_blank">Wikipedia</a>\

1980 Somewhere in Time <a href="https://www.youtube.com/watch?v=9uicvPZSKIM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Somewhere_in_Time_(film)" target="_blank">Wikipedia</a>\

1980 The Shining <a href="https://www.youtube.com/watch?v=S014oGZiSdI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Shining_(novel)" target="_blank">Novel</a>\ <a href="https://en.wikipedia.org/wiki/The_Shining_(film)" target="_blank">Wikipedia</a>\

1983 Videodrome <a href="https://www.youtube.com/watch?v=UFHey3utk0I" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Videodrome" target="_blank">Wikipedia</a>\

1984 The Woman in Red <a href="https://www.youtube.com/watch?v=fcLMGXSyLKw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Woman_in_Red_(1984_film)" target="_blank">Wikipedia</a>\

1984 Children of the Corn <a href="https://www.youtube.com/watch?v=Ks7AwV_uxO0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Children_of_the_Corn_(1984_film)" target="_blank">Wikipedia</a>\

1985 Tampopo <a href="https://www.youtube.com/watch?v=Aw_XfxhzsLY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Tampopo" target="_blank">Wikipedia</a>\

1986 Lucas <a href="https://www.youtube.com/watch?v=UuQZfwWyTWY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Lucas_(film)" target="_blank">Wikipedia</a>\

1987 Wings of desire <a href="https://www.youtube.com/watch?v=hAzzR2Uklok" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Wings_of_Desire" target="_blank">Wikipedia</a>\

1987 Hellraiser <a href="https://www.youtube.com/watch?v=P7TWm3Akw-s" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Hellraiser" target="_blank">Wikipedia</a>\

1988 They Live <a href="https://www.youtube.com/watch?v=jTK8eff1Zsk" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/They_Live" target="_blank">Wikipedia</a>\

1988 976-EVIL <a href="https://www.youtube.com/watch?v=xQT4qB-RFjk" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/976-EVIL" target="_blank">Wikipedia</a>\

1988 The Serpent and the Rainbow <a href="https://www.youtube.com/watch?v=LNRnOcW5yqs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Serpent_and_the_Rainbow_(film)" target="_blank">Wikipedia</a>\

1989 Do the right thing <a href="https://www.youtube.com/watch?v=muc7xqdHudI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Do_the_Right_Thing" target="_blank">Wikipedia</a>\

1991 Highway to Hell <a href="https://www.youtube.com/watch?v=yGiR2TmeNYc" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Highway_to_Hell_(film)" target="_blank">Wikipedia</a>\

1992 Knights Moves <a href="https://www.youtube.com/watch?v=rvDqoxMUroA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Knight_Moves" target="_blank">Wikipedia</a>\

1993 Groundhog day <a href="https://www.youtube.com/watch?v=GncQtURdcE4" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Groundhog_Day_(film)" target="_blank">Wikipedia</a>\

1993 Benny & Joon <a href="https://www.youtube.com/watch?v=AH4Jk_ZJ5OM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Benny_%26_Joon" target="_blank">Wikipedia</a>\

1997 Event Horizon <a href="https://www.youtube.com/watch?v=OVlnER8SxfQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Event_Horizon_(film)" target="_blank">Wikipedia</a>\

1998 Dark city <a href="https://www.youtube.com/watch?v=gt9HkO-cGGo" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Dark_City_(1998_film)" target="_blank">Wikipedia</a>\

2001 Session 9 <a href="https://www.youtube.com/watch?v=LsxkRNvEbhM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Session_9" target="_blank">Wikipedia</a>\

2004 The Woodsman <a href="https://www.youtube.com/watch?v=eMVw1pHVMAw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Woodsman_(2004_film)" target="_blank">Wikipedia</a>\

2004 Primer <a href="https://www.youtube.com/watch?v=-vD-yj9o664" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Primer_(film)" target="_blank">Wikipedia</a>\

2005 Walk the line <a href="https://www.youtube.com/watch?v=RnFrrzg1OEQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Walk_the_Line" target="_blank">Wikipedia</a>\

2006 The live of others <a href="https://www.youtube.com/watch?v=n3_iLOp6IhM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Lives_of_Others" target="_blank">Wikipedia</a>\

2008 The Ramen Girl <a href="https://www.youtube.com/watch?v=N_XU3fHQGHI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Ramen_Girl" target="_blank">Wikipedia</a>\

2008 The Strangers <a href="https://www.youtube.com/watch?v=BbqELQHpmQM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Strangers_(2008_film)" target="_blank">Wikipedia</a>\

2009 Finale <a href="https://www.youtube.com/watch?v=QXnVYcU5khs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Finale_(2009_film)" target="_blank">Wikipedia</a>\

2009 Knowing <a href="https://www.youtube.com/watch?v=rlZdvQwXrOA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Knowing_(film)" target="_blank">Wikipedia</a>\

2010 Blue Valentine <a href="https://www.youtube.com/watch?v=aILx69WrRhQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Blue_Valentine_(film)" target="_blank">Wikipedia</a>\

2010 Incendies <a href="https://www.youtube.com/watch?v=0nycksytL1A" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Incendies" target="_blank">Wikipedia</a>\ <a href="https://www.youtube.com/watch?v=hD9KJL1zt28" target="_blank">Opening scene</a>\ <a href="https://www.youtube.com/watch?v=VchTuRWMw5Q" target="_blank">Bus scene</a>\

2011 Detachment <a href="https://www.youtube.com/watch?v=w7lBleOF9Pw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Detachment_(film)" target="_blank">Wikipedia</a>\

2012 The Great Beauty <a href="https://www.youtube.com/watch?v=Dyt430YkQn0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Great_Beauty" target="_blank">Wikipedia</a>\

2012 Seeking a Friend for the End of the World <a href="https://www.youtube.com/watch?v=T43InzvBm-k" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Seeking_a_Friend_for_the_End_of_the_World" target="_blank">Wikipedia</a>\

2013 The Place Beyond the Pines <a href="https://www.youtube.com/watch?v=G07pSbHLXgg" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Place_Beyond_the_Pines" target="_blank">Wikipedia</a>\

2013 Coherence <a href="https://www.youtube.com/watch?v=kxAOewNzz-8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Coherence_(film)" target="_blank">Wikipedia</a>\

2013 Enemy <a href="https://www.youtube.com/watch?v=FJuaAWrgoUY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Enemy_(2013_film)" target="_blank">Wikipedia</a>\

2013 Upstream Color <a href="https://www.youtube.com/watch?v=SilYsr_3vrA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Upstream_Color" target="_blank">Wikipedia</a>\

2014 Cake <a href="https://www.youtube.com/watch?v=P3IsUOSHlnU" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Cake_(2014_film)" target="_blank">Wikipedia</a>\

2014 Predestination <a href="https://www.youtube.com/watch?v=xxG-YfedrfU" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Predestination_(film)" target="_blank">Wikipedia</a>\

2014 The Wait <a href="https://www.youtube.com/watch?v=13VjX7drnB0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Wait_(2014_film)" target="_blank">Wikipedia</a>\

2014 Mockingbird <a href="https://www.youtube.com/watch?v=37ePQnU9Yc8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Mockingbird_(film)" target="_blank">Wikipedia</a>\

2015 The Martian <a href="https://www.youtube.com/watch?v=ej3ioOneTy8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Martian_(film)" target="_blank">Wikipedia</a>\

2015 The Hallow <a href="https://www.youtube.com/watch?v=8fDo3-mluOs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Hallow" target="_blank">Wikipedia</a>\

2015 The Blackcoat's Daughter <a href="https://www.youtube.com/watch?v=3IH9Jjz3jJA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Blackcoat%27s_Daughter" target="_blank">Wikipedia</a>\

2016 The Monster <a href="https://www.youtube.com/watch?v=tbyCUdzR87Y" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Monster_(2016_film)" target="_blank">Wikipedia</a>\

2016 Personal Shopper <a href="https://www.youtube.com/watch?v=ZLNUGnfGqv8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Personal_Shopper" target="_blank">Wikipedia</a>\

2016 War & Peace <a href="https://www.youtube.com/watch?v=H-BCmUeHE5c" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/War_and_Peace_(2016_TV_series)" target="_blank">Wikipedia</a>\

2016 Swiss Army Man <a href="https://www.youtube.com/watch?v=yrK1f4TsQfM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Swiss_Army_Man" target="_blank">Wikipedia</a>\

2017 Downsizing <a href="https://www.youtube.com/watch?v=UCrBICYM0yM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Downsizing_(film)" target="_blank">Wikipedia</a>\

2017 Tallo Falls <a href="https://www.youtube.com/watch?v=SrVcwvkS1Uc" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt5688868/" target="_blank">IMDb</a>\

2017 Veronica <a href="https://www.youtube.com/watch?v=iMWvbW4n8mE" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Ver%C3%B3nica_(2017_Spanish_film)" target="_blank">Wikipedia</a>\

2017 Time Trap <a href="https://www.youtube.com/watch?v=6T3Z0JTf77k" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Time_Trap_(film)" target="_blank">Wikipedia</a>\

2017 The Shape of Water <a href="https://www.youtube.com/watch?v=XFYWazblaUA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Shape_of_Water" target="_blank">Wikipedia</a>\

2017 The killing of a sacred deer <a href="https://www.youtube.com/watch?v=CQFdGfwChtw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Killing_of_a_Sacred_Deer" target="_blank">Wikipedia</a>\

2017 A ghost story <a href="https://www.youtube.com/watch?v=c_3NMtxeyfk" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/A_Ghost_Story" target="_blank">Wikipedia</a>\

2018 Hereditary <a href="https://www.youtube.com/watch?v=V6wWKNij_1M" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Hereditary_(film)" target="_blank">Wikipedia</a>\

2018 Isle of Dogs <a href="https://www.youtube.com/watch?v=dt__kig8PVU" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Isle_of_Dogs_(film)" target="_blank">Wikipedia</a>\

2018 Le Lion est mort ce soir <a href="https://www.youtube.com/watch?v=1H3oH_P9sRE" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Lion_Sleeps_Tonight_(film)" target="_blank">Wikipedia</a>\

2018 Burning <a href="https://www.youtube.com/watch?v=oihHs2Errwk" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Burning_(film)" target="_blank">Wikipedia</a>\

2018 Border <a href="https://www.youtube.com/watch?v=QMs28A1s1OA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Border_(2018_Swedish_film)" target="_blank">Wikipedia</a>\

2018 Black '47 <a href="https://www.youtube.com/watch?v=q1W4ag4DwBs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Black_%2747" target="_blank">Wikipedia</a>\

2018 The Strangers: Prey at Night <a href="https://www.youtube.com/watch?v=91-Z20uttEk" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Strangers:_Prey_at_Night" target="_blank">Wikipedia</a>\

2018 He's Out There <a href="https://www.youtube.com/watch?v=Bai2ktAZpM8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/He%27s_Out_There" target="_blank">Wikipedia</a>\

2019 Wounds <a href="https://www.youtube.com/watch?v=81uxmIO_lps" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Wounds_(film)" target="_blank">Wikipedia</a>\

2019 Brightburn <a href="https://www.youtube.com/watch?v=oD1vbhicJUY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Brightburn" target="_blank">Wikipedia</a>\

2019 Doctor Sleep <a href="https://www.youtube.com/watch?v=BOzFZxB-8cw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Doctor_Sleep_(2019_film)" target="_blank">Wikipedia</a>\

2019 Svart Cirkel <a href="https://www.youtube.com/watch?v=K3jYTvBQNIo" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt5721636/" target="_blank">IMDb</a>\

2019 The Dead Center <a href="https://www.youtube.com/watch?v=DmC25jd1N5Q" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Dead_Center" target="_blank">Wikipedia</a>\

2019 It own life <a href="https://www.youtube.com/watch?v=6debfd1SUA8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Oliver_Sacks:_His_Own_Life/" target="_blank">Wikipedia</a>\

2019 Ma <a href="https://www.youtube.com/watch?v=eIvbEC8N3cA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Ma_(2019_film)" target="_blank">Wikipedia</a>\

2019 Finale <a href="https://www.youtube.com/watch?v=YOu0g__6s_0" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt5039416/" target="_blank">IMDb</a>\

2019 Harpoon <a href="https://www.youtube.com/watch?v=HxQVhtm-Q9c" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Harpoon_(2019_film)" target="_blank">Wikipedia</a>\

2019 I See You <a href="https://www.youtube.com/watch?v=k72fdSYHHvQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/I_See_You_(2019_film)" target="_blank">Wikipedia</a>\

2019 Fractured <a href="https://www.youtube.com/watch?v=S8obCz5NSog" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Fractured_(2019_film)" target="_blank">Wikipedia</a>\

2019 Us <a href="https://www.youtube.com/watch?v=hNCmb-4oXJA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Us_(2019_film)" target="_blank">Wikipedia</a>\

2019 De repente, el paraíso <a href="https://www.youtube.com/watch?v=X6hXB5yUtys" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/It_Must_Be_Heaven" target="_blank">Wikipedia</a>\

2019 First Cow <a href="https://www.youtube.com/watch?v=SRUWVT87mt8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/First_Cow" target="_blank">Wikipedia</a>\

2019 A Night of Horror: Nightmare Radio <a href="https://www.youtube.com/watch?v=9RMTYzdMiaU" target="_blank">Trailer</a>\ <a href="https://www.theguardian.com/film/2023/apr/26/nightmare-radio-the-night-stalker-review-dj-scares-up-grab-bag-of-horror-stories" target="_blank">The Guardian review</a>\

2020 Greenland <a href="https://www.youtube.com/watch?v=RTODtIQQRpA" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Greenland_(film)" target="_blank">Wikipedia</a>\

2020 Gretel & Hansel <a href="https://www.youtube.com/watch?v=6ZgkHjpUM8w" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Gretel_%26_Hansel" target="_blank">Wikipedia</a>\

2020 Synchronic <a href="https://www.youtube.com/watch?v=XGCrg1OAYfs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Synchronic_(film)" target="_blank">Wikipedia</a>\

2020 The Wild Goose Lake <a href="https://www.youtube.com/watch?v=-oCq5oa8Wzg" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Wild_Goose_Lake" target="_blank">Wikipedia</a>\

2020 Amulet <a href="https://www.youtube.com/watch?v=uV_lUlOc4mQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Amulet_(film)" target="_blank">Wikipedia</a>\

2020 The Antenna <a href="https://www.youtube.com/watch?v=NoMfFPok8Zw" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt8997180/" target="_blank">IMDb</a>\

2020 Possessor <a href="https://www.youtube.com/watch?v=D0Gh9nOIV3w" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Possessor_(film)" target="_blank">Wikipedia</a>\

2020 Koma <a href="https://www.youtube.com/watch?v=5WohqZM2m8U" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Coma_(2020_film)" target="_blank">Wikipedia</a>\

2020 Double world <a href="https://www.youtube.com/watch?v=i4das8_tUUY" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Double_World" target="_blank">Wikipedia</a>\

2020 Tenet <a href="https://www.youtube.com/watch?v=LdOM0x0XDMo" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Tenet_(film)" target="_blank">Wikipedia</a>\

2020 Palm Springs <a href="https://www.youtube.com/watch?v=CpBLtXduh_k" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Palm_Springs_(2020_film)" target="_blank">Wikipedia</a>\

2020 His house <a href="https://www.youtube.com/watch?v=DYY0QJhlXjc" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/His_House" target="_blank">Wikipedia</a>\

2020 Archive <a href="https://www.youtube.com/watch?v=I8WfXdxQ0Cw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Archive_(film)" target="_blank">Wikipedia</a>\

2020 Human nature (documentary) <a href="https://www.youtube.com/watch?v=ageKKE1_1Po" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Human_Nature_(2019_film)" target="_blank">Wikipedia</a>\

2020 Tengo miedo torero <a href="https://www.youtube.com/watch?v=In4hnm9X9LE" target="_blank">Trailer</a>\ <a href="https://es.wikipedia.org/wiki/Tengo_miedo_torero_(pel%C3%ADcula)" target="_blank">Wikipedia</a>\

2020 Bloody Hell <a href="https://www.youtube.com/watch?v=dnPQ7x8HxA0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Bloody_Hell_(2020_film)" target="_blank">Wikipedia</a>\

2020 The Dark and the Wicked <a href="https://www.youtube.com/watch?v=zM-jmNmX50Q" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Dark_and_the_Wicked" target="_blank">Wikipedia</a>\

2021 Psycho Goreman <a href="https://www.youtube.com/watch?v=L4tizc0IAVQ" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Psycho_Goreman" target="_blank">Wikipedia</a>\

2021 Les magnétiques <a href="https://www.youtube.com/watch?v=2nkgxrpcrtg" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt14068864/" target="_blank">Wikipedia</a>\

2021 The Innocents <a href="https://www.youtube.com/watch?v=T8HR-zTRrCM" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Innocents_(2021_film)" target="_blank">Wikipedia</a>\

2021 Carajita <a href="https://www.youtube.com/watch?v=QRclqVbLD9Y" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt12526902/" target="_blank">IMDb</a>\

2021 The Machinery Of Dreams <a href="https://www.youtube.com/watch?v=r3xZmn9Vz_w" target="_blank">Trailer</a>\ <a href="https://pro.imdb.com/title/tt7092846/" target="_blank">IMDb</a>\

2022 RRR <a href="https://www.youtube.com/watch?v=f_vbAtFSEc0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/RRR_(film)" target="_blank">Wikipedia</a>\

2022 Hatching <a href="https://www.youtube.com/watch?v=VtRNqe78x4o" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Hatching_(film)" target="_blank">Wikipedia</a>\

2022 Dual <a href="https://www.youtube.com/watch?v=CpZkNQ0E4YI" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Dual_(2022_film)" target="_blank">Wikipedia</a>\

2022 20th Century Girl <a href="https://www.youtube.com/watch?v=izClpEHwtB8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/20th_Century_Girl" target="_blank">Wikipedia</a>\

2022 Synopsis of Everything Everywhere All at Once <a href="https://www.youtube.com/watch?v=wxN1T1uxQ2g" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Everything_Everywhere_All_at_Once" target="_blank">Wikipedia</a>\

2022 Nope <a href="https://www.youtube.com/watch?v=In8fuzj3gck" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Nope_(film)" target="_blank">Wikipedia</a>\

2022 Ipersonnia <a href="https://www.youtube.com/watch?v=iw_J2ARCH1U" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt16345046/" target="_blank">IMDb</a>\

2022 Sissy <a href="https://www.youtube.com/watch?v=PDImh3sr9Y4" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Sissy_(film)" target="_blank">Wikipedia</a>\

2022 The Electrical Life of Louis Wain <a href="https://www.youtube.com/watch?v=xzDr_tbL-es" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Electrical_Life_of_Louis_Wain" target="_blank">Wikipedia</a>\

2022 Le monde d'hier <a href="https://www.youtube.com/watch?v=rBm3DBZylQ8" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt18361872/" target="_blank">IMDb</a>\

2022 Who Invited Them <a href="https://www.youtube.com/watch?v=Tgavhhzfsg8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Who_Invited_Them" target="_blank">Wikipedia</a>\

2022 A Man Called Otto <a href="https://www.youtube.com/watch?v=eFYUX9l-m5I" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/A_Man_Called_Otto" target="_blank">Wikipedia</a>\

2022 Hypochondriac <a href="https://www.youtube.com/watch?v=bLyA0tRrcMo" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt12186098/" target="_blank">IMDb</a>\

2022 Skinamarink <a href="https://www.youtube.com/watch?v=APQqilSTxz0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Skinamarink" target="_blank">Wikipedia</a>\

2022 La mesita del comedor <a href="https://www.youtube.com/watch?v=oB1lTSxB2j4" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Coffee_Table" target="_blank">Wikipedia</a>\ <a href="https://m.ok.ru/video/6837050149630" target="_blank">Full movie</a>\

2023 Knock at the Cabin <a href="https://www.youtube.com/watch?v=0wiBHEACNHs" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Knock_at_the_Cabin" target="_blank">Wikipedia</a>\

2023 Landscape with Invisible Hand <a href="https://www.youtube.com/watch?v=lAD81wjRnL8" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Landscape_with_Invisible_Hand" target="_blank">Wikipedia</a>\

2022 White Noise <a href="https://www.youtube.com/watch?v=FqJD7ae11mU" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/White_Noise_(2022_film)" target="_blank">Wikipedia</a>\

2023 Music For Black Pigeons (documentary) <a href="https://www.youtube.com/watch?v=zEaH2gA8IoQ" target="_blank">Trailer</a>\ <a href="https://www.imdb.com/title/tt21376876/" target="_blank">IMDb</a>\

2022 Los renglones torcidos de Dios <a href="https://www.youtube.com/watch?v=VpZjyY4wPi0" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/God%27s_Crooked_Lines" target="_blank">Wikipedia</a>\

2023 Beau Is Afraid <a href="https://www.youtube.com/watch?v=PuiWDn976Ek" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Beau_Is_Afraid" target="_blank">Wikipedia</a>\

2023 Cuando acecha la maldad <a href="https://www.youtube.com/watch?v=pOgZ-OJhwbc" target="_blank">Trailer</a>\ <a href="https://es.wikipedia.org/wiki/Cuando_acecha_la_maldad" target="_blank">Wikipedia</a>\

2023 Il sol dell'avvenire <a href="https://www.youtube.com/watch?v=Tj2SzXLyADw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/A_Brighter_Tomorrow" target="_blank">Wikipedia</a>\

2023 Fallen Leaves <a href="https://www.youtube.com/watch?v=a7n8IXlIcS4" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Fallen_Leaves_(film)" target="_blank">Wikipedia</a>\

2023 The Zone of Interest <a href="https://www.youtube.com/watch?v=r-vfg3KkV54" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Zone_of_Interest_%28film%29" target="_blank">Wikipedia</a>\

2023 Los Colonos <a href="https://www.youtube.com/watch?v=rdy--tzaUeo" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/The_Settlers_%282023_film%29" target="_blank">Wikipedia</a>\

2023 Do Not Expect Too Much from the End of the World <a href="https://www.youtube.com/watch?v=kd721-EpgRw" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Do_Not_Expect_Too_Much_from_the_End_of_the_World" target="_blank">Wikipedia</a>\

2024 No Man's Land - Alien Fan Film <a href="https://www.youtube.com/watch?v=h5Fnlq2T0Vg" target="_blank">Full movie</a>\

2024 Monkey Man <a href="https://www.youtube.com/watch?v=aqa3YTtwvaU" target="_blank">Trailer</a>\ <a href="https://en.wikipedia.org/wiki/Monkey_Man_(film)" target="_blank">Wikipedia</a>\
