---
title: "Research"
---

He investigado en varias áreas. Utilizo herramientas de psicología experimental y neurociencia.

En mi línea de investigación sobre **cognición social y emociones** estudié cómo la mirada no solo dirige nuestra atención hacia objetos específicos, sino que también afecta nuestras evaluaciones emocionales de esos objetos, haciendo que nos gusten más los que han sido observados por otros 
<a href="https://doi.org/10.1080/02699931.2014.919899" target="_blank">(REF).</a> Al mismo tiempo me interesé por los correlatos neuronales de estos procesos atencionales y emocionales. Investigué estos procesos usando técnicas electrofisiológicas como la magnetoencefalografía (MEG). Por un lado observé que el procesamiento atencional ocurre muy temprano en el tiempo <a href="https://doi.org/10.1016/j.neuropsychologia.2017.12.029" target="_blank">(REF)</a> y además que hay distintas rutas cerebrales donde se combinan de manera distintiva la información de la mirada y la información de las emociones <a href="https://doi.org/10.1093/scan/nss141" target="_blank">(REF).</a>

Me he interesado también por la **experiencia estética y social asociada con el arte y la ficción**. Otro fenómeno que he investigado es como ser espectador de una performance en vivo puede llevar a que ritmos cognitivos y fisiológicos se sincronizen entre espectadores y bailarines. Este fenómeno de sincronización podría influir en la experiencia emocional y perceptiva de los espectadores <a href="https://doi.org/10.3389/fnhum.2015.00179" target="_blank">(REF).</a> También he examinado cómo las personas crean y se sumergen en mundos imaginarios, como en el caso del Fanfic, conectando estos procesos con las capacidades cognitivas que usamos para entender y navegar en interacciones sociales <a href="https://doi.org/10.1017/S0140525X21002235" target="_blank">(REF).</a>

He investigado en las áreas de la **psicopatología y psiquiatría**. Como parte de mi formación en bioquímica formé parte de estudio que evaluó cómo un antidepresivo modula cambios conductuales y moleculares inducidos por estrés crónico en un modelo animal de depresión <a href="https://doi.org/10.1097/FBP.0b013e32832c70d9" target="_blank">(REF).</a> En esta misma línea, estudié los efectos diferenciados de la sertralina en conducta tipo depresiva inducida por estrés o por corticosterona <a href="https://doi.org/10.1016/j.pbb.2010.08.001" target="_blank">(REF).</a> En humanos, he formado parte de investigaciones que buscan analizar la ideación suicida y la labilidad afectiva en pacientes con trastorno depresivo mayor <a href="https://doi.org/10.1016/j.jad.2020.04.004" target="_blank">(REF).</a> En una avenida cercana, he explorado el rol del control imitativo en procesos emocionales y socio-cognitivos (¿que pasaría si se pudiera entrenar?; <a href="https://doi.org/10.1037/emo0001442" target="_blank">REF).</a> y si se podrían usar estas habilidades de control imitativo para predecir rasgos autistas <a href="https://doi.org/10.1016/j.actpsy.2023.104056" target="_blank">(REF).</a> Más recientemente, investigué si las habilidades para controlar la imitación podrían estar asociadas con experiencias psicóticas, y así evaluar su potencial como predictores tempranos de psicopatología <a href="10.3389/fpsyt.2024.1470030" target="_blank">(REF).</a>

Otra línea de investigación se enfoca en la **cognición motora y la agencia**. Más específicamente, en los aspectos psicológicos y neuronales asociados con nuestras acciones y el control percibido sobre ellas. He investigado aspectos neuronales del rol de la fluidez en la selección de acciones y su impacto en el sentido de agencia implícito (intentional binding; <a href="https://doi.org/10.1016/j.cortex.2020.01.013" target="_blank">REF).</a> Además, he investigado la interacción entre el contacto por la mirada y el sentido de agencia <a href="https://doi.org/10.1016/j.concog.2019.102794" target="_blank">(REF).</a> También he hecho revisiones bibliográficas revisado varios aspectos neurobiológicos asociados con la agencia <a href="https://ojs.uc.cl/index.php/psykhe/article/view/42093" target="_blank">(REF)</a> y a nivel mas neuronal he revisado el rol de los ritmos cerebrales gamma en el control motor <a href="https://doi.org/10.3389/fnhum.2021.787157" target="_blank">(REF).</a>

## Experimentos

En la actualidad tengo varios estudios en curso que se realizan bajo el alero de proyectos más grandes y en el contexto de tesis de pregrado y postgrado. Algunos de mis experimentos online se describen aquí (intenta algunos):

<a href="https://ayq5whrkjb.cognition.run" target="_blank">¿Cómo afecta la música en nuestras emociones?</a> \
¿Cómo puede algo tan abstracto como la música influir en nuestras emociones de manera tan poderosa? Durante la vida, la música nos acompaña en momentos clave, modificando nuestro estado emocional con solo unos pocos acordes o cambios de ritmo. Esta investigación examina cómo diferentes características de la música pueden evocar cambios en nuestras emociones.

<a href="https://2nowtl2igi.cognition.run" target="_blank">¿Cómo se expresan las emociones en el cuerpo?</a> \
Las emociones no solo se sienten en la mente; también se viven en el cuerpo. Este estudio investiga cómo las emociones se manifiestan en sensaciones físicas distribuidas a lo largo del cuerpo. La pregunta que motiva esta investigación es si hay patrones consistentes de activación corporal asociados a las emociones.

<a href="https://cdprtxiob2.cognition.run" target="_blank">¿Cómo tomamos decisiones?</a> \
Cuando tomamos decisiones rara vez contamos con toda la información necesaria. Este estudio plantea una pregunta esencial: ¿cómo combinamos nuestras suposiciones iniciales con nueva evidencia para tomar decisiones en situaciones inciertas? En el escenario planteado, se invita a los participantes a usar tanto la información previa como los datos sensoriales actuales para evaluar un resultado.

<a href="https://oiaiuaylos.cognition.run" target="_blank">¿Cómo percibimos las emociones en los rostros?</a> \
En la vida cotidiana, interpretamos las emociones de las personas basándonos en sus expresiones faciales, pero ¿qué factores pueden influir en esta interpretación? Este estudio examina cómo las emociones percibidas en los rostros pueden estar influenciadas por diferentes factores.

<a href="https://efhgseqwcc.cognition.run/" target="_blank">¿Cómo respondemos a estímulos sociales?</a> \
En las interacciones humanas, estamos constantemente expuestos a estímulos provenientes de otras personas, y nuestras respuestas pueden ocurrir rápidamente, a veces sin que lo notemos. Este experimento se centra en analizar cómo ciertos estímulos sociales influyen en nuestra conducta, incluso cuando no estamos plenamente conscientes de nuestra reacción. 
